import pygame

Play = pygame.image.load("assets/play.png")
Play = pygame.transform.scale(Play, (200, 100))
Play_H = pygame.image.load("assets/play_h.png")
Play_H = pygame.transform.scale(Play_H, (200, 100))
Quit = pygame.image.load("assets/quit.png")
Quit = pygame.transform.scale(Quit, (200, 100))
Quit_H = pygame.image.load("assets/quit_h.png")
Quit_H = pygame.transform.scale(Quit_H, (200, 100))
Yes = pygame.image.load("assets/yes.png")
Yes = pygame.transform.scale(Yes, (100, 50))
Yes_H = pygame.image.load("assets/yes_h.png")
Yes_H = pygame.transform.scale(Yes_H, (100, 50))
No = pygame.image.load("assets/no.png")
No = pygame.transform.scale(Yes, (100, 50))
No_H = pygame.image.load("assets/no_h.png")
No_H = pygame.transform.scale(Yes_H, (100, 50))
Menu_BG = pygame.image.load("assets/menu_bg.png")
Menu_BG = pygame.transform.scale(Menu_BG, (1200, 800))
Title = pygame.image.load("assets/title.png")
Title = pygame.transform.scale(Title, (400, 100))